// Generated by gencpp from file ideasclinic/class_info.msg
// DO NOT EDIT!


#ifndef IDEASCLINIC_MESSAGE_CLASS_INFO_H
#define IDEASCLINIC_MESSAGE_CLASS_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ideasclinic
{
template <class ContainerAllocator>
struct class_info_
{
  typedef class_info_<ContainerAllocator> Type;

  class_info_()
    : header()
    , symbol(0.0)  {
    }
  class_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , symbol(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _symbol_type;
  _symbol_type symbol;





  typedef boost::shared_ptr< ::ideasclinic::class_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ideasclinic::class_info_<ContainerAllocator> const> ConstPtr;

}; // struct class_info_

typedef ::ideasclinic::class_info_<std::allocator<void> > class_info;

typedef boost::shared_ptr< ::ideasclinic::class_info > class_infoPtr;
typedef boost::shared_ptr< ::ideasclinic::class_info const> class_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ideasclinic::class_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ideasclinic::class_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ideasclinic

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'ideasclinic': ['/home/kaeun/catkin_ws/src/ideasclinic/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ideasclinic::class_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ideasclinic::class_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ideasclinic::class_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ideasclinic::class_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ideasclinic::class_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ideasclinic::class_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ideasclinic::class_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6204dca736ea35ff5d011038bc5006ed";
  }

  static const char* value(const ::ideasclinic::class_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6204dca736ea35ffULL;
  static const uint64_t static_value2 = 0x5d011038bc5006edULL;
};

template<class ContainerAllocator>
struct DataType< ::ideasclinic::class_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ideasclinic/class_info";
  }

  static const char* value(const ::ideasclinic::class_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ideasclinic::class_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 symbol\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ideasclinic::class_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ideasclinic::class_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.symbol);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct class_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ideasclinic::class_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ideasclinic::class_info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "symbol: ";
    Printer<double>::stream(s, indent + "  ", v.symbol);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IDEASCLINIC_MESSAGE_CLASS_INFO_H
